# Generated by Django 5.2.12 on 2026-03-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_votes', models.IntegerField(default=0)),
                ('satisfactory_votes', models.IntegerField(default=0)),
                ('bad_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
