# Generated by Django 5.2.12 on 2026-03-25 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lives',
            fields=[
                ('person_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.lives')),
            ],
        ),
    ]
